(define-module (pathgro base path-slashes)
               #:export (append-slashes prepend-slashes unappend-slashes unprepend-slashes))

(use-modules (pathgro util stdio))

(define (prepend-slashes slst)
  (if (null? slst)
    '()
    (if (string=? (substring/shared (car slst) 0 1) "/")
      (cons (car slst) (prepend-slashes (cdr slst)))
      (cons (string-append/shared "/" (car slst)) (prepend-slashes (cdr slst))))))

(define (unprepend-slashes slst)
  (if (null? slst)
    '()
    (if (string=? (substring/shared (car slst) 0 1) slash) 
      (cons (substring/shared (car slst) 1 (string-length (car slst))) (unprepend-slashes (cdr slst)))
      (cons (car slst) (unprepend-slashes (cdr slst))))))

(define (append-slashes slst)
  (if (null? slst)
    '()
    (if (string=? (substring/shared (car slst) 0 1) slash)
      (cons (car slst) (append-slashes (cdr slst)))
      (cons (string-append/shared slash (car slst)) (append-slashes (cdr slst))))))

(define (unappend-slashes slst)
  (if (null? slst)
    '()
    (if (string=? (substring/shared (car slst) (- (string-length (car slst)) 1) (string-length (car slst))) slash)
      (cons (substring/shared 0 (- (string-length (car slst)) 1) (unappend-slashes (cdr slst))))
      (cons (car slst) (unappend-slashes (cdr slst))))))
