(define-module (pathgro base prepend-slashes)
  #:export (prepend-slashes unprepend-slashes))

(define (prepend-slashes slst)
  (if (null? slst)
    '()
    (let ((acar (car slst)))
      (if (string=? (substring acar 0 1) "/")
        (cons acar (prepend-slashes (cdr slst)))
        (cons (string-append "/" acar) (prepend-slashes (cdr slst)))))))

(define (unprepend-slashes slst)
  (if (null? slst)
    '()
    (let ((acar (car slst)))
      (if (string=? (substring acar 0 1) "/")
        (cons (substring acar 1 (string-length acar)) (unprepend-slashes (cdr slst)))
        (cons acar (unprepend-slashes (cdr slst)))))))
