#!/usr/bin/env bash

# Global guile share folder
export GUILE_SHARE=/usr/share/guile
# Local guile cache folder
export HOME_CACHE_GUILE=~/.cache/guile
# Path to the `linuxbrew` cellar folder
export HOME_LINUXBREW_GUILE=~/.linuxbrew/Cellar/guile
# Location where `git clone` created the pathgro repository 
export PATHGRO_GIT_REPO=~/GIT/decal/pathgro

nice find "$GUILE_SHARE" -type d -name 'pathgro' -exec rm -frdv {} \;
nice find "$HOME_CACHE_GUILE" -type d -name 'pathgro' -exec rm -frdv {} \;
nice find "$HOME_LINUXBREW_GUILE" -type d -name 'pathgro' -exec rm -frdv {} \;
nice find "$PATHGRO_GIT_REPO" -type f -name '*.go' -exec rm -fv {} \;

exit 0
